version: "3.9"

services:
  jocker:
    image: jolielang/jocker
    network_mode: host                     # Binds directly to the host network
    privileged: true
    volumes:
      - /var/run:/var/run
    security_opt:
      - label:disable
    ulimits:
      nofile: {soft: 65536, hard: 65536}
    logging: {driver: none}

  catalog:
    image: jfn/function_catalog
    network_mode: host                     # Binds directly to the host network
    environment:
      - FUNCTION_CATALOG_LOCATION=socket://0.0.0.0:8002
      - ETCD_LOCATION=${ETCD_LOCATION}     # Injected by the Swarm bootstrapper
      - VERBOSE=true

  provisioner:
    image: jfn/provisioner
    network_mode: host                     # Binds directly to the host network
    environment:
      # Because Jocker spawns Executors with --network host, they share the host's 
      # network namespace and can reach the Provisioner simply via localhost.
      - ADVERTISE_LOCATION=socket://localhost:8001
      - PROVISIONER_LOCATION=socket://0.0.0.0:8001
      - FUNCTION_CATALOG_LOCATION=socket://localhost:8002
      - DOCKER_NETWORK=host                # Tell Jocker to spawn Executors on the host network
      - MIN_RUNNERS=1
      - CALLS_PER_RUNNER=2
      - CALLS_FOR_PROMOTION=3
      - CALLS_PER_SINGLETON=12
      - VERBOSE=true
      - DEBUG=false
    depends_on:
      - jocker
      - catalog
