FROM jolielang/jolie:edge-alpine

WORKDIR /app
RUN apk add --no-cache openjdk21-jdk

COPY *.ol /app
RUN mkdir jfn
COPY Checksum.java /app/jfn

RUN javac -cp $JOLIE_HOME/jolie.jar:$JOLIE_HOME/lib/libjolie.jar jfn/Checksum.java
RUN jar cvf checksum.jar jfn/Checksum.class
RUN mkdir lib && mv checksum.jar lib/checksum.jar

RUN apk del openjdk21-jdk

VOLUME /data
EXPOSE 8002
ENV FUNCTION_CATALOG_LOCATION "socket://0.0.0.0:8002"
ENV VERBOSE false

CMD jolie function_catalog_loader.ol
