events {
    worker_connections 1024;
}

stream {
    upstream jfn_gateways {
        server ${WOKER1_IP}:8000;
        server ${WOKER2_IP}:8000;
    }

    server {
        listen 8000;
        proxy_pass jfn_gateways;
        proxy_timeout 30s;
        proxy_connect_timeout 5s;
    }
}

